### ISSUE TITLE
Invalid language switching links on ultrabug.github.io

### ISSUE THREAD

**Issue by marcelstoer** [ultrabug/mkdocs-static-i18n#1]
On https://ultrabug.github.io/mkdocs-static-i18n/ the language switching links at the bottom of the start page are broken.

"Get to the FR version" points to https://ultrabug.github.io/fr when it should point to https://ultrabug.github.io/mkdocs-static-i18n/fr/ instead. Same issue for EN and DEFAULT.

**Comment by ultrabug** [comment]
Thanks a lot @marcelstoer ! indeed the relative path of gh-pages tricked my local tests :+1:
