### ISSUE TITLE
Logo Link to current language

### ISSUE THREAD

**Issue by ChrisBlankDe** [ultrabug/mkdocs-static-i18n#109]
If we click on the on the logo icon we navigate back to the index page of the **default** language. is there an possibility to go back to the index page of the **current** language?
i think that would provide a better ux for end users.

**Comment by ultrabug** [comment]
Hello @ChrisBlankDe 

Ofc it is possible, I've opened a PR #111 to address this.

If that's possible for you, please test it, else I'll just merge since I added and checked this works with tests ;)
