### ISSUE TITLE
pdf link on default language pages

### ISSUE THREAD

**Issue by ChrisBlankDe** [ultrabug/mkdocs-static-i18n#110]
thanks for the great i18n plugin and thanks that you support other useful plugins. 👍
With mkdocs-with-pdf there is currently the problem that the pdf for the default language is not provided cleanly.

rendered site:
de/pdf/document.pdf
en/pdf/document.pdf
pdf/document.pdf <-- missing

as a workaround we do a copy job but i think this should be handled by i18n plugin

**Comment by adamkusmirek** [comment]
How would the desired output look like?

For example, assuming that the default language is `en`:

Option 1:

de/pdf/document.pdf
pdf/document.pdf <- this contains `en` content

Option 2:

de/pdf/document.pdf
en/pdf/document.pdf
pdf/document.pdf <- this contains `en` content again

In case it is option 2, `default/pdf/document.pd` should probably be symlinked/aliased somehow to avoid having duplicate pdf files.

**Comment by ChrisBlankDe** [comment]
i think option 2 would be solve this since the pdf should be accessable from the default dir and the specific language folder.
since our pdfs are getting bigger and bigger a symlinked/aliased would be great.

Another valid solution would be just to change the pdf link in the footer of the default language to the specific language folder
e.g. from `https://mydomain.com/pdf/document.pdf` to `https://mydomain.com/en/pdf/document.pdf` if `en `is the default language

**Comment by ultrabug** [comment]
Hello @ChrisBlankDe 

I was surprised to read your issue so I tested it again and I can't reproduce your problem since I do have all the pdfs (even the default one) on my output :

```
├── en
│   ├── assets
│   │   └── image_non_localized.png
│   ├── image.fake
│   ├── image.png
│   ├── index.html
│   ├── pdf
│   │   └── document.pdf
│   ├── topic1
│   │   └── named_file
│   │       └── index.html
│   └── topic2
│       ├── 1.1.filename.html
│       └── index.html
├── fr
│   ├── assets
│   │   └── image_non_localized.png
│   ├── image.fake
│   ├── image.png
│   ├── index.html
│   ├── pdf
│   │   └── document.pdf
│   ├── topic1
│   │   └── named_file
│   │       └── index.html
│   └── topic2
│       ├── 1.1.filename.html
│       └── index.html
├── image.fake
├── image.png
├── index.html
├── pdf
│   └── document.pdf
├── search
│   └── search_index.json
├── sitemap.xml
├── sitemap.xml.gz
├── topic1
│   └── named_file
│       └── index.html
└── topic2
    ├── 1.1.filename.html
    └── index.html

24 directories, 63 files
```

This is confirmed by the build logs :

```
INFO     -  Adding 'fr' to the 'plugins.search.lang' option
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/alexys/github/mkdocs-static-i18n/site
INFO     -  Translated navigation to fr
INFO     -  Number headings up to level 3.
INFO     -  Generate a table of contents up to heading level 2.
INFO     -  Generate a cover page with "default_cover.html.j2".
INFO     -  Converting <img> alignment(workaround).
INFO     -  Rendering for PDF.
INFO     -  Output a PDF to "/home/alexys/github/mkdocs-static-i18n/site/pdf/document.pdf".
INFO     -  Converting 3 articles to PDF took 3.4s
INFO     -  Building en documentation
INFO     -  Number headings up to level 3.
INFO     -  Generate a table of contents up to heading level 2.
INFO     -  Generate a cover page with "default_cover.html.j2".
INFO     -  Converting <img> alignment(workaround).
INFO     -  Rendering for PDF.
INFO     -  Output a PDF to "/home/alexys/github/mkdocs-static-i18n/site/en/pdf/document.pdf".
INFO     -  Converting 6 articles to PDF took 6.4s
INFO     -  Building fr documentation
INFO     -  Number headings up to level 3.
INFO     -  Generate a table of contents up to heading level 2.
INFO     -  Generate a cover page with "default_cover.html.j2".
INFO     -  Converting <img> alignment(workaround).
INFO     -  Rendering for PDF.
INFO     -  Output a PDF to "/home/alexys/github/mkdocs-static-i18n/site/fr/pdf/document.pdf".
INFO     -  Converting 9 articles to PDF took 9.6s
INFO     -  Documentation built in 10.03 seconds
```

I'm using `mkdocs-with-pdf version 0.9.3`

**Comment by Maddin-619** [comment]
I have the same problem:
```
INFO     -  Building documentation...
INFO     -  Setting the default 'theme.locale' option to 'de'
INFO     -  Adding 'en' to the 'plugins.search.lang' option
INFO     -  Cleaning site directory
INFO     -  Building de documentation
INFO     -  Number headings up to level 3.
INFO     -  Generate a table of contents up to heading level 2.
INFO     -  Generate a cover page with "default_cover.html.j2".
INFO     -  Converting <img> alignment(workaround).
INFO     -  Rendering on `Headless Chrome`(execute JS).
INFO     -  Rendering for PDF.
INFO     -  Output a PDF to "/tmp/mkdocs_8dec2hh6/de/pdf/docu.pdf".
INFO     -  Converting 24 articles to PDF took 7.7s
INFO     -  Building en documentation
INFO     -  Number headings up to level 3.
INFO     -  Generate a table of contents up to heading level 2.
INFO     -  Generate a cover page with "default_cover.html.j2".
INFO     -  Converting <img> alignment(workaround).
INFO     -  Rendering on `Headless Chrome`(execute JS).
INFO     -  Rendering for PDF.
INFO     -  Output a PDF to "/tmp/mkdocs_8dec2hh6/en/pdf/docu.pdf".
INFO     -  Converting 36 articles to PDF took 14.2s
INFO     -  Number headings up to level 3.
INFO     -  Generate a table of contents up to heading level 2.
INFO     -  Generate a cover page with "default_cover.html.j2".
INFO     -  Converting <img> alignment(workaround).
INFO     -  Rendering on `Headless Chrome`(execute JS).
INFO     -  Rendering for PDF.
INFO     -  Output a PDF to "/tmp/mkdocs_8dec2hh6/en/pdf/docu.pdf".
INFO     -  Converting 36 articles to PDF took 20.6s
INFO     -  Documentation built in 22.09 seconds

```

Since the pdf plugin output path gets mutated for each language it effects the "original/default" build steps. The "original" pdf generation step should use the "original" output path (without the language directory), but because it gets executed at last, it uses the last mutated pdf output path for a specific language. As a result the pdf for these language gets overwritten with a wrong pdf.

**Comment by ultrabug** [comment]
Can I have access to a repository where I can reproduce this @Maddin-619 ?

Along with a complete `mkdocs.yml` config file?

**Comment by Maddin-619** [comment]
https://github.com/Maddin-619/docu

**Comment by Maddin-619** [comment]
@ultrabug i have found out the cause of the problem:
The order of the plugins in the `mkdocs.yml` plugins array makes the different. i18n plugin must be the last one!

**Comment by ultrabug** [comment]
Thanks for looking into it @Maddin-619 ; 

To be precise, should it be the **last** one or simply **after the with-pdf one**?

I'd bet on "being after" is enough

**Comment by Maddin-619** [comment]
Yes u are right.

What should we do now? Would nice if we have an order independent solution. Or we just add the fact to the readme.

Also the default language is unnecessarily rendered twice. For big docu this could be a waste of resources.

**Comment by ultrabug** [comment]
> What should we do now? Would be nice if we have an order independent solution. Or we just add the fact to the readme.

I can have i18n detect its order and change it on the fly

> Also the default language is unnecessarily rendered twice. For big docu this could be a waste of resources.

I'd like to keep magic to its minimum; i18n can't start overcoming every other plugins implementations. Doing the best we can without interfering too much with other plugins is the safe way forward.

**Comment by ultrabug** [comment]
This proved to me more tricky than expected since with-pdf messes with other plugins events...

Please check and review #112 which should fix the problem, no matter the with-pdf position :+1: 

Thanks

**Comment by ultrabug** [comment]
@Maddin-619 @ChrisBlankDe friendly ping; I intend to merge this this week.
