### ISSUE TITLE
Multi-level  nav translation problem

### ISSUE THREAD

**Issue by EvilMask** [ultrabug/mkdocs-static-i18n#113]
Hello @sukki37 ,

I meet a problem similar to #96 . My nav setting is like:
![image](https://user-images.githubusercontent.com/3178725/170286875-5b6365af-074a-4f69-bb2f-7bd421a32575.png)
I have translations for `Home`, `Reference`, `Changelog`, but only `Home` and `Changelog` have been translated for the default language (ja).
![image](https://user-images.githubusercontent.com/3178725/170287774-6a25b05a-0f5a-4270-897b-381e1ab6f18d.png)
And this is my i18n settings.

If I change the default titles to `ja` and make `en` translations, everything works well.

Report this just in case.

**Comment by ultrabug** [comment]
Hello @EvilMask ; thanks for reporting this

I'm gonna investigate

**Comment by ultrabug** [comment]
@EvilMask it's actually quite hard to reproduce... Do you have any public repository where I can test this?

**Comment by ultrabug** [comment]
Ok @EvilMask scratch that, I found out what the problem was !

Can you check #119 maybe? I added tests to reproduce so if no report in a week, I'll merge & release that fix

Thanks again!
