### ISSUE TITLE
Search duplicates

### ISSUE THREAD

**Issue by mastercoms** [ultrabug/mkdocs-static-i18n#129]
https://docs.mastercomfig.com/dev/

Search for `textures`

It will come up with every language's translation page in the search results, search_reconfigure or not.

https://github.com/mastercomfig/mastercomfig/blob/develop/mkdocs.yml#L5

**Comment by ultrabug** [comment]
Explanation is written in the README docs here mate: https://github.com/ultrabug/mkdocs-static-i18n#compatibility-with-the-search-plugin

**Comment by mastercoms** [comment]
Yes I have read that, but I tried to use `search_reconfigure: false` and `search_reconfigure: true`, both have duplicates, even though it said the feature can be disabled. And also, "will try to be smart and deduplicate the pages", but it doesn't seem like this is the case.

**Comment by ultrabug** [comment]
It's being "smart" between the default_language and the same language if defined twice. Apart from that there's little it can do against a single index enforced by the upstream search plugin I'm afraid.

**Comment by mastercoms** [comment]
But for example, there is no translation for the modules.md page for anything but Russian. But it displays the English version of the page for each language. Is there really no way to exclude pages which are copied from the default language?

**Comment by ultrabug** [comment]
I'll have to check what we could do, that's a good point to be smarter ;)

**Comment by mastercoms** [comment]
It's alright, I understand as an open source maintainer myself :) No need to worry

**Comment by ultrabug** [comment]
Hi @mastercoms I believed I have found some great optimizations on the search plugin deduplication

Could you please test with https://github.com/ultrabug/mkdocs-static-i18n/pull/139 and report back?

Thanks!

**Comment by mastercoms** [comment]
Yes, it works, thank you so much!
