### ISSUE TITLE
Page title is reset

### ISSUE THREAD

**Issue by mastercoms** [ultrabug/mkdocs-static-i18n#130]
I assume this is done to have the same path as the default language, but it makes localization of the page title not possible

Note how in the diff here where I have re-enabled the i18n plugin, social cards are going back to their english titles. https://github.com/mastercomfig/mastercomfig/commit/dea4f1a14ec354001e1cbdfbfe9e86550f1d0418#diff-933fd042fcab2e74c5ad1267ed83b09c2771c6ec31d5c5fd39901d8884821429

**Comment by ultrabug** [comment]
Hello @mastercoms I'm sorry but I don't have access to mkdocs-material insiders version so I can't tell about your problem.

From what I see here after cloning your repo, if I navigate to the Benchmarks page in English, switch to Russian (which has a translation for this page) I see the page title translated to `Тест` as expected.

**Comment by mastercoms** [comment]
For me the page title in the browser tab and navigation is in english, it's just the markdown title that has the russian

**Comment by ultrabug** [comment]
Wait, you are not [translating your navigation are you?](https://github.com/ultrabug/mkdocs-static-i18n#translating-navigation)

**Comment by mastercoms** [comment]
Ah, I see, no I didn't do that. I don't know how I missed that in the documentation. This fixes the problem. Thank you!
