### ISSUE TITLE
Support jupyter notebook(ipynb) files

### ISSUE THREAD

**Issue by yeemh** [ultrabug/mkdocs-static-i18n#135]
thanks for the great i18n plugin 👍

I'm trying to use mkdocs-jupyter plugin for rendering ipynb files, and figured out ipynb files don't show if I use with this plugin.
Is there any way to use both plugins?

```
plugins:
    - i18n
    - mkdocs-jupyter
```
made possible to show ipynb in default page, but not in other languages

**Comment by yeemh** [comment]
Searched for why and found `file.is_documentation_page()` may make ipynb as static files.
Mkdocs defines
[files.py](https://github.com/mkdocs/mkdocs/blob/88df80e1f4a617a621365d681e3859b522172822/mkdocs/structure/files.py#L249)
```python
def is_documentation_page(self) -> bool:
        """Return True if file is a Markdown page."""
        return utils.is_markdown_file(self.src_uri)
```
[utils/\_\_init\_\_.py](https://github.com/mkdocs/mkdocs/blob/88df80e1f4a617a621365d681e3859b522172822/mkdocs/utils/__init__.py#L35),
[utils/\_\_init\_\_.py is_markdown_file](https://github.com/mkdocs/mkdocs/blob/88df80e1f4a617a621365d681e3859b522172822/mkdocs/utils/__init__.py#L196)
```python
markdown_extensions = (
    '.markdown',
    '.mdown',
    '.mkdn',
    '.mkd',
    '.md',
)

def is_markdown_file(path):
    """
    Return True if the given file path is a Markdown file.
    https://superuser.com/questions/249436/file-extension-for-markdown-files
    """
    return path.endswith(markdown_extensions)
```
So I've tried to inclue ipynb when checking `file.is_documentation_page()`, but it didn't work.
Is there any other part that affects ipynb not working?

**Comment by ultrabug** [comment]
Hello @yeemh sorry for the late reply.

Do you have a public repo where this can be tested? I need a reproductible environment to be helpful I'm afraid.

It's hard for a plugin to be compatible with whatever the others plugins are doing as you can understand :(

**Comment by ultrabug** [comment]
Please reopen if you want to help in reproduction.
