### ISSUE TITLE
Could not find alternate for the default version of page 'index.md'

### ISSUE THREAD

**Issue by mastercoms** [ultrabug/mkdocs-static-i18n#167]
I'm not sure why I'm getting this warning now. In my root docs folder, I have `index.es.md`, `index.fr.md`, `index.pt.md`, `index.ru.md` and `index.md`.

```
WARNING  -  could not find 'en' alternate for the default version of page 'index.md'
WARNING  -  could not find 'pt' alternate for the default version of page 'index.md'
WARNING  -  could not find 'ru' alternate for the default version of page 'index.md'
WARNING  -  could not find 'es' alternate for the default version of page 'index.md'
WARNING  -  could not find 'fr' alternate for the default version of page 'index.md'
WARNING  -  could not find 'tr' alternate for the default version of page 'index.md'
```

**Comment by ultrabug** [comment]
Just since you upgraded to 0.52? does it do the same using 0.51?

I'm confused..

**Comment by sennewood** [comment]
I just wanted to post the same issue :)

These are my package versions:
```
mkdocs==1.4.2
mkdocs-material==8.5.10
mkdocs-material-extensions==1.1.1
mkdocs-static-i18n==0.51
```

**Comment by ultrabug** [comment]
I need more information than this please : I need a way to reproduce your problem to be truly helpful.

- mkdocs.yml
- public (hopefully) repository to try and understand your problem

Thanks :+1:

**Comment by mastercoms** [comment]
https://github.com/mastercomfig/mastercomfig/tree/develop/docs

https://github.com/mastercomfig/mastercomfig/actions/runs/3602279440/jobs/6069092830#step:16:32

**Comment by mastercoms** [comment]
First time I can see it happen was 2022 Nov 15 16:34 UTC

**Comment by mastercoms** [comment]
So, I can only assume it was introduced in this commit: https://github.com/ultrabug/mkdocs-static-i18n/commit/d98cc0486344127eb50465070608068760ae1cca

**Comment by sennewood** [comment]
I went down all versions until the site got generated again and it's working again with: `0.49`.
