### ISSUE TITLE
Incorrect creation of language folder on mkdocs build

### ISSUE THREAD

**Issue by magneticcore** [ultrabug/mkdocs-static-i18n#17]
mkdocs: 1.1.2
mkdocs-material: 7.0.7
mkdocs-static-i18n: 0.5
OS: Windows

I just try to build a i18n site with your plugin and the result of the build from docs is quiet strange:

docs:
<pre>
├─ index.fr.md
└─ index.md
mkdocs.yml
</pre>

And the command 'mkdocs build' produces:

site:
<pre>
├─fr
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├─index.fr
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├─index.html
└─ index.html
</pre>

The index.html file for french language is not directly under fr folder, but inside a index.fr folder!?!

mkdocs.yml:
<pre>
site_name: Test
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        fr: français
theme:
  name: material
  features:
    - navigation.expand
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Français
      link: /fr/
      lang: fr
nav:
  - index.md
</pre>

**Comment by magneticcore** [comment]
The mentionned problem is present only if use_directory_urls: true, with use_directory_urls: false, it works correctly

**Comment by ultrabug** [comment]
hello @magneticcore

I think you run into the same issue as expressed in #7 by @cacrespo, do you confirm?

**Comment by magneticcore** [comment]
Yes, I confirm that it is the same problem than #7 if use_directory_urls: true
If use_directory_urls: false, another problem happen. I will open an new issue for this, but I believe correlate to #7 .

**Comment by magneticcore** [comment]
And we agree that the version 0.5 of your plugin doesn't integrate yet a correction for this problem of windows path.

**Comment by ultrabug** [comment]
Yes indeed, I'm working on a CI + tests + fix mate, I should be able to spare some time on it tonight

**Comment by ultrabug** [comment]
fixed in #13 and version 0.6, thanks !

**Comment by magneticcore** [comment]
I can confirm on my side with Windows operating system that my problem initially described in this topic has been resolved with the last version(s)
