### ISSUE TITLE
Language switch for non dedicated version for the default language build

### ISSUE THREAD

**Issue by Stanzilla** [ultrabug/mkdocs-static-i18n#19]
Currently when using the mode to not build a dedicated version for the default language, the default language does not show up in the language switcher dropdown which makes it hard to return to it. So I'd suggest adding something to get the default language and then updating the example for it.

Material also now has a native language selector (https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector) so my current code looks like this:

```html
<!-- Site language selector -->
    {% if config.extra.alternate %}
      <div class="md-header__option"></form>
        <div class="md-select">
          {% set icon = config.theme.icon.alternate or "material/translate" %}
          <span class="md-header__button md-icon">
            {% include ".icons/" ~ icon ~ ".svg" %}
          </span>
          <div class="md-select__inner">
            <ul class="md-select__list">
              <li class="md-select__item">
                <a href="/" class="md-select__link">
                  English
                </a>
              </li>
              {% for lang, display in config.plugins.i18n.config.languages.items() -%}
                <li class="md-select__item">
                  <a href="/{{ lang }}/" class="md-select__link">
                    {{ display }}
                  </a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    {% endif %}
```

**Comment by ultrabug** [comment]
I'm not sure why you actually are doing this `{% for lang, display in config.plugins.i18n.config.languages.items() -%}` since it seems like mkdocs-material claims to handle this for you?

Why not go fully with the mkdocs-material language selector?

**Comment by ultrabug** [comment]
I switched to it, and it works great, no more partials ! https://ultrabug.github.io/mkdocs-static-i18n/

**Comment by Stanzilla** [comment]
I don't remember actually :D You do have english in there twice now though, as default and english

**Comment by ultrabug** [comment]
Yep I did it on purpose for the sake of the demo so that people get the idea, since it's static in mkdocs.yml you're free to choose :)

**Comment by Stanzilla** [comment]
One problem I see is that it does not retain the page you are currently on

**Comment by ultrabug** [comment]
Might be something squidfunk can deal with on mkdocs-material?

TBH, I don't expect people to switch language all the time anyway..
