### ISSUE TITLE
When set use_directory_urls: false , it confused

### ISSUE THREAD

**Issue by zimocode** [ultrabug/mkdocs-static-i18n#2]
set use_directory_urls: false in mkdocs.yml
``` yml
use_directory_urls: false
```

create test.en.md, test.fr.md:
``` bash
docs
├── test.fr.md
├── test.en.md
```
then 
``` bash
mkdocs serve
```

just test these urls:

|||
|-|-|
|http://127.0.0.1:8000/test.en.html    |ok|
|http://127.0.0.1:8000/test.fr.html      |err|
|http://127.0.0.1:8000/test.html         |err|
|-|-|
|http://127.0.0.1:8000/en/test.html        | err|
|http://127.0.0.1:8000/en/test.en.html    |ok|
|http://127.0.0.1:8000/en/test.fr.html      |err|
|-|-|
|http://127.0.0.1:8000/fr/test.html         |err|
|http://127.0.0.1:8000/fr/test.en.html    |err|
|http://127.0.0.1:8000/fr/test.fr.html      |ok|

**Comment by ultrabug** [comment]
Hi @zimocode, thanks for your interest in this plugin

That's an option I didn't think about indeed. It should not be too hard to fix, I'll have a look :)

**Comment by ultrabug** [comment]
@zimocode just to be sure, your table shows the current results of the pages but I want to acknowledge that what you expect is :

|||
|-|-|
|http://127.0.0.1:8000/test.en.html    |err|
|http://127.0.0.1:8000/test.fr.html      |err|
|http://127.0.0.1:8000/test.html         |ok|
|-|-|
|http://127.0.0.1:8000/en/test.html        |ok|
|http://127.0.0.1:8000/en/test.en.html    |err|
|http://127.0.0.1:8000/en/test.fr.html      |err|
|-|-|
|http://127.0.0.1:8000/fr/test.html         |ok|
|http://127.0.0.1:8000/fr/test.en.html    |err|
|http://127.0.0.1:8000/fr/test.fr.html      |err|

Am I right ?

**Comment by ultrabug** [comment]
Ok I looked into it and thanks to your insights I believe to have addressed the issue.

I created a test suite to validate the structure to prevent any regression in the future. Thanks again mate!

Available on 0.3 ;)

**Comment by zimocode** [comment]
wating for the pip update.
thanks.

**Comment by zimocode** [comment]
It works
thanks.
