### ISSUE TITLE
Generate language selector links with use_directory_urls in mind

### ISSUE THREAD

**Issue by Delivator** [ultrabug/mkdocs-static-i18n#21]
We use [use_directory_urls](https://www.mkdocs.org/user-guide/configuration/#use_directory_urls) `true` on our build, because our webserver doesn't use index files, so we need the full file path.

I think the links generated for the language selector should acknowledge that option to generate the links like this when `use_directory_urls` is set to true: `/fr/index.html`, `/de/index.html` etc.

**Comment by ultrabug** [comment]
Thanks for the input @Delivator, that's a very good point!

I have this done locally but want to add tests before releasing it, I'm on it mate

**Comment by ultrabug** [comment]
@Delivator MR is up, do you have the possibility to test it and validate that it works as expected?

**Comment by Delivator** [comment]
@ultrabug How can I test this? I only know how to install via PIP.

**Comment by ultrabug** [comment]
@Delivator don't bother then, with my tests added I'm confident enough; I'm gonna merge and release 0.11 then you can give a final confirmation here plz

**Comment by Delivator** [comment]
@ultrabug Hey sorry to bother you. I totally got it wrong.
Mkdocs adds adds the `/index.html` to the links if `use_directory_urls: false` not `true`. ([Docs for reference](https://www.mkdocs.org/user-guide/configuration/#use_directory_urls))

So here we would need to check `if config.get("use_directory_urls") is False:`

https://github.com/ultrabug/mkdocs-static-i18n/blob/3a9efa8c8c68d9626409c99fb0732971ad3a1802/mkdocs_static_i18n/plugin.py#L210

Sorry again.

**Comment by ultrabug** [comment]
No it's me who apologizes @Delivator I saw it during development but I lost it because of the problems I ran into for the tests...

version 0.12 is released to fix that !

PS: like the project? spread the word and give it a :star: if you feel like it <3

**Comment by Delivator** [comment]
@ultrabug Awesome, thanks a lot!
Yeah it works really well! We should probably add a page to our docs mentioning all the awesome plugins we use :)
