### ISSUE TITLE
GitHub Pages don't redeploy

### ISSUE THREAD

**Issue by kamilkrzyskow** [ultrabug/mkdocs-static-i18n#212]
I noticed that even though the plugin got updated, the https://ultrabug.github.io/mkdocs-static-i18n/ page wasn't rebuilt.
The last build is from mkdocs-material version 7 and it lacks sitemaps etc.
So maybe redeploy it with updated theme / plugin version. ✌️

**Comment by ultrabug** [comment]
Done for version 1.0.0

I shall make this automatic using GH actions indeed

Thanks
