### ISSUE TITLE
Possibility to process other files like file.<language>.<extension>

### ISSUE THREAD

**Issue by magneticcore** [ultrabug/mkdocs-static-i18n#22]
It would be interesting within the context of your plugin to process not only file.\<language>.md files, but also others whose suffix would be identical in term of naming.

Example:
`versions.fr.json => fr/versions.json`

To authorize this functionality and therefore limit the choice of files according to their extension, a setting could be added:

alternate_files_extension: json, txt, jpeg

If empty, then no file other than file.\<language>.md is processed.

**Comment by ultrabug** [comment]
Hello @magneticcore 

That's a very interesting proposal indeed, thanks for taking the time to write it down to improve the plugin :+1: 

IMHO I'd rather plural the `extensions` part of the proposed configuration variable name (but I'm not English native so maybe I'm wrong).

```
alternate_file_extensions:
  - json
  - txt
  - jpeg
```

Would that sound good?

**Comment by acDev-User1** [comment]
alternate_file_extensions in place of alternate_files_extension: yes, definitively.

That sounds very good!

**Comment by magneticcore** [comment]
alternate_file_extensions in place of alternate_files_extension: Yes, definitively

That sounds very good!

**Comment by zLucPlayZ** [comment]
Would be very helpful. This would also be a solution/opportunity to make it so, you fallback to other file types, if the language specific one doesnt exist.

E.g. I have a "index.html" in my root. It works, but only with the default language selected. Would be nice if it also fallsback to this, whenever there is no language specific "index.html" like "index.de.html" when having another language selected.

**Comment by ultrabug** [comment]
I'm sorry @zLucPlayZ I'm not sure I understand what you mean?

FYI @magneticcore I'll get back to this when I'm done on my (big) pull request to add localization support to mkdocs. Thanks for your patience.

**Comment by zLucPlayZ** [comment]
@ultrabug in a nutshell, will this also bring the fallback support for the defined alternate file extensions? Like its implemented for md files rn?

**Comment by magneticcore** [comment]
If I understand correctly @zLucPlayZ and there is fr as alternative language.

Example 1: As I requested
```
versions.fr.json => fr/versions.json
```

Example 2: As versions.fr.json doesn't exist, but versions.json yes, versions.json is copied in fr folder (like existing md file scenario):
```
versions.json => fr/versions.json
```

**Comment by ultrabug** [comment]
Yes @zLucPlayZ it will behave the same as for the md files (thx @magneticcore)

**Comment by ultrabug** [comment]
Implemented in #26, test & report appreciated <3

**Comment by ultrabug** [comment]
version 0.13 is there mates

**Comment by magneticcore** [comment]
Very good, thank you!
