### ISSUE TITLE
Config value 'plugins' - Unrecognised configuration name

### ISSUE THREAD

**Issue by gallaher** [ultrabug/mkdocs-static-i18n#222]
I have got a new laptop (installed i18n : 0.4.6, mkdocs : 1.4.2, material : 9.1.8 and python : 3.11.3) and I was planning to update my multi-language documentation in MkDocs. The page can be found here: https://help.racetracker.no/. I cloned the repository, but running the page locally I see that the language selector has disappeard from the top ribbon and a new bullet point is inserted on top of the page:

-  {'name': 'English', 'build': True, 'site_name': 'Race Tracker Manuals'}

I also get these three warnings when running "mkdocs serve" in the command terminal:
WARNING  -  Config value 'plugins': Plugin 'i18n' option 'default_language_only': Unrecognised configuration name:
            default_language_only
WARNING  -  Config value 'plugins': Plugin 'i18n' option 'docs_structure': Unrecognised configuration name:
            docs_structure
WARNING  -  Config value 'plugins': Plugin 'i18n' option 'nav_translations': Unrecognised configuration name:
            nav_translations

Code from my mkdocs.yml:
plugins:
    - search
    - offline
    - mkdocs-video
    - i18n:
        default_language: !ENV [DEFAULT_LANGUAGE, "nb"]
        default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
        docs_structure: suffix
        languages:
           default:
            name: Default (nb)
            build: true
           en:
            name: English
            build: true
            site_name: "Race Tracker Manuals"
           nb:
            name: Norsk
            build: true
            site_name: "Race Tracker Manualer (nb)"
        nav_translations:
           en:
            Hjem: Home
            Tracking: Tracking
            Tidtakingsutstyr: Timing Equipment
            Passivt system: Passive system
            Hvordan bruke vår 4G/GSM-tracker: How to use a 4G/GSM-tracker
            Hvordan bruke admin: How to use Admin
            Forberede en konkurranse: Prepare a competition
            Kartet: The map

Is this a problem some of you have encountered before? Are you able to lead me in the right direction or do you need more information?

Regards,
Martin

**Comment by ultrabug** [comment]
Hello @gallaher 

Can you format the config sample better or link me to the file so I can have a look at it?

**Comment by gallaher** [comment]
Hi @ultrabug I have tried to make permalink:
https://github.com/gallaher/my-project/blob/bda3e3244fa071e83b3495b2e2e653320dcc9c41/mkdocs.yml#L1-L101

I included all the lines in the mkdocs.yml

**Comment by ultrabug** [comment]
@gallaher your project is private, I can't access it

**Comment by ultrabug** [comment]
Most likely something is wrong with your environment. Please try to reinstall `pip install mkdocs-static-i18n` by hand?

**Comment by gallaher** [comment]
and what do you mean with environment?

**Comment by ultrabug** [comment]
I cloned your project, installed everything and it works as intended.

```
$ pip freeze
certifi==2022.12.7
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
ghp-import==2.1.0
idna==3.4
Jinja2==3.1.2
lxml==4.9.2
Markdown==3.3.7
MarkupSafe==2.1.2
mergedeep==1.3.4
mkdocs==1.4.2
mkdocs-material==9.1.8
mkdocs-material-extensions==1.1.1
mkdocs-static-i18n==0.56
mkdocs-video==1.5.0
packaging==23.1
Pygments==2.15.1
pymdown-extensions==9.11
python-dateutil==2.8.2
PyYAML==6.0
pyyaml_env_tag==0.1
regex==2023.3.23
requests==2.29.0
six==1.16.0
urllib3==1.26.15
watchdog==3.0.0
```

**Comment by ultrabug** [comment]
@gallaher I dunno, something must have gone wrong with your installation. I strongly suggest you add a `requirements.txt` file to your project with your dependencies (such as the pip freeze I just pasted above).

**Comment by gallaher** [comment]
@ultrabug Thank you! It works now :-)

**Comment by ultrabug** [comment]
Good, enjoy!
