### ISSUE TITLE
incompatibility with mkdocs-material-insiders

### ISSUE THREAD

**Issue by gnaegi** [ultrabug/mkdocs-static-i18n#231]
We recently upgrade to the mkdocs material insider program and ever since the language chooser disappeared. I tried to debug why  and could trace it down to the plugin.py script at the very beginning: 

During the basic import and init code the i18n plugin tries to identified the languages: lang.split(".html")[0]. 
For whatever reason the "lang" variable is not available in my case. Thus, later in the except code the material version is set to none. If I manually set the version to 7.1.1 everything works again. 

I don't know why the lang variable is empty when using the insider or maybe this is a side effect of something else. Has someone any clue where the lang variable comes from and how I could fix this?

**Comment by ultrabug** [comment]
Hello @gnaegi ; which version of insiders are you using?

**Comment by gnaegi** [comment]
Always the latest. When I debug the variable `material_version` get the value `9.1.18+insiders.4.36.1` as the value. I think it would be save to split with the "+" sign and just use the first part. That would be awesome!

**Comment by ultrabug** [comment]
I'm happy to announce release v1.0.0 of the `mkdocs-static-i18n` plugin!

Please check it out and reopen if needed as this should fix the problem :)
