### ISSUE TITLE
Can I set different themes for each language?

### ISSUE THREAD

**Issue by Chen-Luan** [ultrabug/mkdocs-static-i18n#234]
I'm currently referring to the documentation at https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme to customize the theme by creating a 404.html file under the overrides path. However, I'm uncertain about how to apply different themes to different language pages. I would greatly appreciate any guidance on this matter. Thank you in advance for your assistance!

**Comment by ultrabug** [comment]
Hello @Chen-Luan 

You can't change the whole theme per language (tho [it might become possible in the future](https://github.com/ultrabug/mkdocs-static-i18n/pull/216))
