### ISSUE TITLE
Possibility of translate section titles

### ISSUE THREAD

**Issue by Caetan95** [ultrabug/mkdocs-static-i18n#24]
Thanks for the plugin, great job! I was wondering if it's possible to have somehow a translation of the section titles on the nav (your `Topic 1`,  `Topic 2`) depending on the language, as you can see below:

**English version**
![english](https://user-images.githubusercontent.com/71437950/117809284-4937dd80-b25e-11eb-83d3-51f820cea502.png)

**French version**
![francais](https://user-images.githubusercontent.com/71437950/117809298-4d63fb00-b25e-11eb-980b-016412e88cf8.png)

**Comment by ultrabug** [comment]
Hi @Caetan95 thanks for your kind words, I'm glad you find this plugin useful :+1: 

I guess that what you are asking for is feasible but I'd like to hear about how you would imagine this feature should be presented/being made available to users?

**Comment by ultrabug** [comment]
I will work on #22 and give your point a thought

We have been discussing a possible merge with @sim6 of mkdocs-i18n and I proposed to incorporate his features in this plugin so maybe this could be added too and fit your needs as well at the same time.

**Comment by Caetan95** [comment]
Thank you so much for your work! I think it can end up being a very complete plugin

**Comment by mic4ael** [comment]
Hey @ultrabug thanks for all of this. I would like to know one thing though. Are you planning to implement something similar to the first point @Caetan95 suggested or we should rather wait for the possible merge of the two plugins? I am wondering whether we should implement something quick for now and wait for a more complete solution or we can just wait until you soon perform the merge.

**Comment by ultrabug** [comment]
@mic4ael hi

> implement something similar to the first option

You mean moving to a file structure or to a nav translation config? I believe more in the nav translation config than requiring users to change all their docs structure so I'd rather implement a new config for this.

**Comment by mic4ael** [comment]
Hi! I meant supporting the suggested file structure (of course with a few limitations) just as a quick workaround. However, this might indeed cause some problems in the future once nav translation config is supported. Maybe we could try implementing something akin to the `translate_nav` and contribute it to the project?

**Comment by ultrabug** [comment]
Yes @mic4ael ofc contributions are welcome!

For now I'd like #26 to get in before adding a new option.

**Comment by ultrabug** [comment]
@Caetan95 @mic4ael hi, quick heads-up to tell you that #26 is in and version 0.13 released

This issue is next then :+1:

**Comment by ultrabug** [comment]
@Caetan95 @mic4ael could you please check and try #28 please?

It was easier to implement than expected, hope you like it

**Comment by mic4ael** [comment]
Thanks a lot @ultrabug ! That is awesome :D I will give it a try tomorrow and will let you know the outcome ;)

**Comment by magneticcore** [comment]
What is the command pip to take this commited code?

**Comment by ultrabug** [comment]
@magneticcore you have to
- uninstall mkdocs-static-i18n from your virtualenv
- clone this repo
- checkout the issue_24 branch
- pip install -e .

and test :)
