### ISSUE TITLE
Link setting error on homepage (`index.md` `index.html`)

### ISSUE THREAD

**Issue by RonaldLN** [ultrabug/mkdocs-static-i18n#261]
When building a webpage using mkdocs-material and using the mkdocs-static-i18n plugin to set multiple language selection functions, the link settings on the homepage (`index.md` `index.html`) are incorrect
![无标题](https://github.com/ultrabug/mkdocs-static-i18n/assets/120019179/69c96678-713f-419f-82f2-caa40c67a8b7)
![无标题2](https://github.com/ultrabug/mkdocs-static-i18n/assets/120019179/49ac1777-581a-4012-9af3-274f484e320b)

**Comment by ultrabug** [comment]
Hello @RonaldLN 

This is because you are missing the `site_url` configuration in your `mkdocs.yml` file.

You should add: `site_url: https://ronaldln.github.io/MyPamphlet`

**Comment by RonaldLN** [comment]
> Hello @RonaldLN
> 
> This is because you are missing the `site_url` configuration in your `mkdocs.yml` file.
> 
> You should add: `site_url: https://ronaldln.github.io/MyPamphlet`

oh, it works, thanks you very much!! @ultrabug  😆
