### ISSUE TITLE
Is there a way to preserve the language selection?

### ISSUE THREAD

**Issue by janvanveldhuizen** [ultrabug/mkdocs-static-i18n#282]
The audience of my website is a mixed group of Dutch and international people. The default language of my website is English, which can be irritating for the Dutch users as they have to switch to Dutch every time. Would it be possible to store the language preference in local storage and use that the next time the website is opened?

**Comment by ultrabug** [comment]
Hello @janvanveldhuizen ; that's actually a theme feature, not something that this plugin can provide and ensure will work with every theme out there I'm afraid.

**Comment by squidfunk** [comment]
For Material for MkDocs, see https://github.com/squidfunk/mkdocs-material/issues/6466
