### ISSUE TITLE
[BUG] Windows install UnicodeDecodeError

### ISSUE THREAD

**Issue by luolingchun** [ultrabug/mkdocs-static-i18n#29]
`pip install mkdocs-static-i18n` 
in Windows10，output follow errors:
```cmd
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    long_description=read("README.md"),
  File "setup.py", line 11, in read
    return (Path(__file__).resolve().parent / fname).read_text()
  File "C:\Program Files\Python38\lib\pathlib.py", line 1233, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2335: illegal multibyte sequence
```

Just add `encoding` to read_text(), like this:
```python
return (Path(__file__).resolve().parent / fname).read_text(encoding='utf-8')
```

**Comment by ultrabug** [comment]
Thanks for your report @luolingchun 

cc @cacrespo did you ever encounter this?

**Comment by ultrabug** [comment]
Thanks @luolingchun this is part of version 0.14

**Comment by ultrabug** [comment]
Consider spreading :heart: and :star: the project if you like it mate!

**Comment by cacrespo** [comment]
Hi @ultrabug!! 
I just installed it in a virtual environment and had no problem...
Although now that I see: it is version 0.14 and it should be fixed 😆
