### ISSUE TITLE
[Question] INFO - Selected en None File(...) output

### ISSUE THREAD

**Issue by maybenikhil** [ultrabug/mkdocs-static-i18n#299]
Hello - I have this plugin installed on a (currently) single language project, that I am planting on localizing in the near future. A recent issue/minor annoyance (occured on update from 121, I believe I have found the line of code) that causes this output so I'm curious if this is intended behavior. The output is as follows:

```bash
docs-docs-1  | INFO    -  mkdocs_static_i18n: Selected en None File(src_uri='index.md', dest_uri='index.html', name='index', url='./')
```

The lines that outputs this are: 
https://github.com/ultrabug/mkdocs-static-i18n/blob/0b492e11fa0cd8c716bb2e570a8fb4cc93765cf1/mkdocs_static_i18n/reconfigure.py#L649-L651

I'm curious if this intended behavior? We use index.md as our homepage, and can definitely change the name if needed.

**Comment by kamilkrzyskow** [comment]
You could create a hook that adds a filter to omit that message, similar to how it's done in the plugin for time logging:
https://github.com/ultrabug/mkdocs-static-i18n/blob/0b492e11fa0cd8c716bb2e570a8fb4cc93765cf1/mkdocs_static_i18n/plugin.py#L216-L221

**Comment by ultrabug** [comment]
Indeed that's totally my fault, I meant to have this as a debug level log I apologize.

**Comment by ultrabug** [comment]
this is being addressed in https://github.com/ultrabug/mkdocs-static-i18n/pull/305
