### ISSUE TITLE
Search plugin just works for the default language

### ISSUE THREAD

**Issue by Caetan95** [ultrabug/mkdocs-static-i18n#31]
Hello again. Sorry for the inconvenience, but we found another problem in the plugin, now is the integration with the [search plugin](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/). The thing is that the search function only works with the default language, so when we are in a different language it searches only in the default language, ignoring the other languages. I think the problem is with the plugin itself, which is maybe disabling something that the search plugin needs, as long as for example [this other one works](https://mkdocs-i18n.gitlab.io/mkdocs-i18n/).

Do you know what the problem could be and if it is easy to solve?

Thank you very much.

**Comment by ultrabug** [comment]
@Caetan95 hi; sure it should not be a problem if you can provide me with an example and what you expect from it?

**Comment by Caetan95** [comment]
Thanks for your quick reply @ultrabug we really appreciate it.

I would expect to search in each language separately, so depending on which language I am, it will search into it.

Currently, the behavior is that it always searches in the default language (in your example, in English), and if I change to français it will continue searching in the English version. In addition, if I search for some French word (in the French version) that is present in the text it can't find anything, since as far as I understand it just searches into English files (the default language) without taking into account the language that is currently selected.

**1. English language search**
![image](https://user-images.githubusercontent.com/71437950/120812628-73bf4280-c54d-11eb-9955-e48f284381e7.png)

**2. French language search (no results)**
![image](https://user-images.githubusercontent.com/71437950/120812700-846fb880-c54d-11eb-8a92-c5b405654f30.png)

**3. French language search (searching for English stuff)**
![image](https://user-images.githubusercontent.com/71437950/120812945-bf71ec00-c54d-11eb-8cea-61beeafd0c64.png)

So taking into account this example, I would expect that **2. French language search (no results)** shows some results (as the word décrite appears in the files) and it would be nice too that **3. French language search (searching for English stuff)** doesn't show any results from other languages (just the selected one, which is French in this screenshot), but maybe this last one is not as critical as the second one, the French language search with no results (by extension all languages that are not the default).

I would like to thank you again for your collaboration :)

**Comment by ultrabug** [comment]
FYI @Caetan95 the way the search plugin is implemented prevents us from having a search index per language.

I'm almost done with this, it works good on mkdocs 1.1.2 but not on 1.2... looking into it now.

**Comment by Caetan95** [comment]
Hello @ultrabug, thanks for your commitment. Just FYI, I have been testing the new mkdocs 1.2 release with your plugin and I haven't found any other conflict (apart from those that we have already discuss).

Thanks again for your work :)

**Comment by ultrabug** [comment]
version 0.15 is out mate, thanks!
