### ISSUE TITLE
[Bug] Fonts are not being loaded

### ISSUE THREAD

**Issue by adamkusmirek** [ultrabug/mkdocs-static-i18n#35]
After adding this plugin all requests to the `fonts/` folder result in a 404.

I am using the `readthedocs` theme and mkdocs 1.2.1

After inspecting the generated `style.css`, I noticed that all font paths are relative and of the form: `.../fonts/<fontfile>`, maybe resolving this is a problem?

**Comment by ultrabug** [comment]
Hi @adamkusmirek thanks for your report.

Strange that the live local server did not catch it, could you detail how to reproduce this please?

**Comment by adamkusmirek** [comment]
I just tried incrementally adding all the components to a clean mkdocs project with `mkdocs-static-i18n` and the culprit apprently is `readthedocs`

Since you nowhere specified that this theme is supported I guess this "bug" is more an incompatibility.
Sorry about bothering you.

Maybe I'll manage to make `readthedocs` work anyways with your plugin, in which case I'll let you know so you can maybe add support for it.

**Comment by ultrabug** [comment]
Very interesting finding, we shall add some tests that reproduce the problem before and demonstrate that the fix is good and will not happen again too please!

**Comment by adamkusmirek** [comment]
Agreed, I'll add some tests later. The PR is in draft state until then..

**Comment by Stanzilla** [comment]
I can repro this as well, if you go to https://docs.coregames.com/tutorials/curves/#interpolation-type and click on the image to open the lightbox, the buttons (fonts) in the top right are missing.

**Comment by ultrabug** [comment]
Fixed thanks to you!

**Comment by ultrabug** [comment]
version 0.17 is out !

**Comment by adamkusmirek** [comment]
yay, just updated my project and things seem to work!
