### ISSUE TITLE
Would appreciate help with this plugin

### ISSUE THREAD

**Issue by Andre601** [ultrabug/mkdocs-static-i18n#46]
When creating the following structure:
```
├─ api
│  ├─ index.de.md
│  └─ index.en.md
├─ index.de.md
└─ index.en.md
```
and I want to link from `index.<lang>.md` to `api/index.<lang>.md` could I just do `[link](/api/index.md)` and the plugin would adjust the link to point to the right file of the same language, or would I need to directly reference the file (`api/index.en.md`)?

**Comment by inouthack** [comment]
> 
> and I want to link from `index.<lang>.md` to `api/index.<lang>.md` could I just do `[link](/api/index.md)` and the plugin would adjust the link to point to the right file of the same language, or would I need to directly reference the file (`api/index.en.md`)?

(i'm not the author) on reading the documentation it gives the impression that this controlled by the mkdocs.yml configuration

```
      - i18n:
            default_language: en
            languages:
                 de: Deutsch
```
in short, "plugin would adjust the link to point to the right file of the same language".

**Comment by ultrabug** [comment]
Hi @Andre601 

> could I just do [link](/api/index.md) and the plugin would adjust the link to point to the right file of the same language

Yes exactly, you can reference any page or asset without their .<lang>.<extension> to ease your development

This is demonstrated in the demo website [and explained here](https://github.com/ultrabug/mkdocs-static-i18n#referencing-localized-content-in-your-markdown-pages)

Hope this helps :)

**Comment by ultrabug** [comment]
@Andre601 is that alright with you? Do you need anything else?

If not, I'll close this issue in 1 day

**Comment by Andre601** [comment]
It's good. Thanks for the info.
