### ISSUE TITLE
Sitemap support

### ISSUE THREAD

**Issue by Stanzilla** [ultrabug/mkdocs-static-i18n#47]
So mkdocs does generate a sitemap.xml for all pages but currently the extra language pages generated by this plugin do not get added to it, it seems. 

```xml
<url>
    <loc>http://www.example.com/docs/</loc>
    <xhtml:link rel="alternate" hreflang="de" href="http://www.example.com/de/"/>
  </url>
```

This example Is probably what it should do, not sure if plugins can even change the sitemap generation though.

**Comment by ultrabug** [comment]
Hi @Stanzilla 

I have no clue about how it's generated, I'll have a look when I can

**Comment by ultrabug** [comment]
Okay I think I found how to do it :+1: 

Please test #54 , it contains #48 as well

Once validated by you, I'll merge everything ;)

Cheers

**Comment by ultrabug** [comment]
@Stanzilla since you asked on matrix, what is your opinion on this topic please?

**Comment by Stanzilla** [comment]
> @Stanzilla since you asked on matrix, what is your opinion on this topic please?

So for me this needs to have some kind of support in mkdocs itself, as in, changing to the template to make it i18n "aware", but I'm also not an expert on the matter :/
