### ISSUE TITLE
[Enhancement Request] Language switcher that stays on the current page

### ISSUE THREAD

**Issue by skullydazed** [ultrabug/mkdocs-static-i18n#52]
Currently when you configure the language switcher it always takes you back to the root of the site. It would be a lot nicer if it took you to the same page in that language.

For a concrete example, say you are on this page:

https://ultrabug.github.io/mkdocs-static-i18n/topic1/named_file/

When you change the language to French you are taken to this page:

https://ultrabug.github.io/mkdocs-static-i18n/fr/

I would like the user to instead be taken to this page:

https://ultrabug.github.io/mkdocs-static-i18n/fr/topic1/named_file/

**Comment by ultrabug** [comment]
I reworked it a bit again, my local test on your `platform-documentation` works good now @Stanzilla ; can you give it another try?

**Comment by Stanzilla** [comment]
> I reworked it a bit again, my local test on your `platform-documentation` works good now @Stanzilla ; can you give it another try?

https://612e4d8fda61db30d1063593--manticore-docs.netlify.app/

**Comment by ultrabug** [comment]
Thanks, that looks good to me, does it to you?

**Comment by Stanzilla** [comment]
> Thanks, that looks good to me, does it to you?

I was going to reply "no" because the initial change does not work but everything else aftwards does!

Steps:

- https://612e4d8fda61db30d1063593--manticore-docs.netlify.app/
- Click "Install Core"
- Switch to French
--> Page is not retained

Everything else afterwards works though.

**Comment by ultrabug** [comment]
Navigating in developer mode and killing the cache fixes the problem. I think you experience this because you use `navigation.instant`

**Comment by Stanzilla** [comment]
> Navigating in developer mode and killing the cache fixes the problem. I think you experience this because you use `navigation.instant`

Oh yeah, I do use that. So would mkdocs-material need to add something to support this feature with instant mode?

**Comment by ultrabug** [comment]
@squidfunk would you have an opinion on this please? you can have a peek at the link @Stanzilla provided above

**Comment by squidfunk** [comment]
@ultrabug I have only briefly checked @Stanzilla's solution, but this feature is already on Material for MkDocs' [roadmap](https://squidfunk.github.io/mkdocs-material/insiders/#8000-scotch-bonnet) as "stay on page when switching languages". This means that I'll revisit this functionality at some point in the future. Note that I haven't used this plugin, yet, but my current educated guess is that a solution based on the idea of "one project per language" gives more flexibility, as noted [here](https://github.com/ultrabug/mkdocs-static-i18n/issues/57) and [here](https://github.com/squidfunk/mkdocs-material/discussions/2346).

Any solution provided natively as part of Material for MkDocs will, of course, work with instant loading.

**Comment by Stanzilla** [comment]
Not sure if related, but navigation.instant also causes a bug where the html's `lang` attribute will sometimes not change back when you switch from a non-default to the default lang.

**Comment by squidfunk** [comment]
Instant loading doesn't replace the whole HTML but only [specific sections](https://github.com/squidfunk/mkdocs-material/blob/a633f12e096f7a64185630b8b68e52e0479b274a/src/assets/javascripts/integrations/instant/index.ts#L275-L286), so it's no real surprise that the HTML attribute is not replaced. If you wish to replace other parts, you can use code similar to the one I just linked, but beware that `document$` will also emit on initial load, which is why the `skip(1)` is in place.

**Comment by ultrabug** [comment]
> a solution based on the idea of "one project per language" gives more flexibility, as noted here and here.

In my experience, having a low barrier entry that can match 80%+ of needs is fine. Not everyone scale their documentation at a point where they need to follow a whole guide to handle all their localized versions.

The good thing for the mkdocs community is that both solutions exist, and that's what matters most imho.
