### ISSUE TITLE
[feedback] Large site friction

### ISSUE THREAD

**Issue by skullydazed** [ultrabug/mkdocs-static-i18n#57]
I don't know how much of this will be actionable, but I'm in the middle of converting a largish site over to mkdocs right now and trying to come up with a workable i18n/l10n story. I gave mkdocs-static-i18n a good try but in the end it's not a fit for us.

## Background

I'm attempting to migrate <https://docs.qmk.fm/> from docsify to a static site generator. The current docsify structure looks something like this:

* `/docs/page.md` - English
* `/docs/fr-fr/page.md` - French

To start working with mkdocs-static-i18n I put together a site structure that looks like this: <https://github.com/qmk/qmk_mkdocs/tree/mkdocs-static-i18n>

(Apologies for the rough repo, I accidentally deleted my branch that had all the tweaks and fixes to make that work well.)

That repo contains roughly 145 English markdown documents and nearly 350 documents across 8 languages overall. 

### Speed

The first pain point is speed- on my relatively beefy desktop with an NVME SSD it takes roughly 5 seconds to build the English language docs. It takes nearly 2 minutes to build every language. We can alleviate that pain for people working on English documentation, but anyone working on a translation is looking at 2+ minutes of waiting every time they press save.

### Navigation Translation

Tying the navigation translation to the current English text means that changes to navigation titles have to be done in multiple places. That's one more thing we need to catch in PR reviews.

It also prevents changing the structure of the navigation in a way that makes sense for native speakers. For example, our [French translation](https://docs.qmk.fm/#/fr-fr/) specifically calls out the pages that have and have not been translated.

### Can't have pages that don't exist in the primary language

I spent a lot of time cleaning up errors like this:

    Exception: mkdocs-static-i18n is expecting one of the following files: [PosixPath('getting_started_build_tools.md'), PosixPath('getting_started_build_tools.en.md')]

We have some files that are translation specific. Requiring a corresponding English language document is in some cases nonsensical and in other cases just redundant.

### Everything is in one directory

With everything in one directory it's harder on everyone. People working on the English language site have to sort through all the non-English files. Since our translations are incomplete you can't be sure if the next English doc is 2 lines down or 5 lines down when you're scanning through the list.

If you want to see what has and hasn't been translated for your particular language you end up writing a bunch of shell to filter through the list of files.

## What are we using instead?

I'm still in the experimental phase of this project, but right now the clear winner is what I have on [the main branch here](https://github.com/qmk/qmk_mkdocs). This basically builds a structure where every language is a separate site, and I use some custom github actions to assemble them into a whole structure. 

I don't have a good story for language or version switching yet, but I think I can solve those with some mkdocs-material theme customization work.

**Comment by ultrabug** [comment]
Hi @skullydazed 

First of all I want to thank you for trying out mkdocs-static-i18n and thank you even more for taking on your time to write this detailed feedback, that's very kind of you and much appreciated!

Indeed this plugin is quite young and started out as a way to address a need that was hanging for years in the mkdocs community so it's not a one-solution-fits-all kind of plugin.

That being said, before I can take on each of your points individually I want to ask : is your choice not to use this plugin made or do you want this feedback to be a base on a possible collaboration to improve things? (speed for instance is indeed something I want to address).

**Comment by skullydazed** [comment]
Our choice is not final yet, but even if it was I'd be open to replacing a collection of hacks and workarounds with a better solution. :slightly_smiling_face: We just completed a breaking change cycle, which means I have 1-2 months to finish sorting our migration out before I need to get it merged into the develop branch.

I'll let you take the lead on where you want to go with this. The qmk_mkdocs repo I linked is experimental and will no longer be needed once we complete our migration, so it's easy for me to leave that and the mkdocs-static-i18n branch open indefinitely. Even if we don't end up using mkdocs-i18n-static I'd be happy to help improve it for others who do.

**Comment by Stanzilla** [comment]
## Build Speed

I think build speed is definitely an issue and valid concern. @ultrabug did a lot of perf improvements and it already is way better than it was before but I still disable multi lang builds for the local developer environment. I control this via the `mkdocs.yml` config file like so: `default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, true]`. 

So only people who work on the non-default language set that environment variable and take the build speed hit.


## Navigation Translation

I'm not using this feature currently but I would probably rely on your theme using the name parameter from the yaml frontmatter in your files for the menu names. This makes sure that the titles are in the same files as the content and updating them is only done in one place.

## Can't have pages that don't exist in the primary language

Personally not something that I encountered because it's the other way around for me, we only have a very small subset of pages translated at the moment.

## Everything is in one directory

I can totally see the pro's and con's for that. For me, it has not been a problem because, as I said above, we only translated a very small subset of files at the moment. But if possible, supporting a different folder structure, like having /lang/ subfolders directly, would help?

**Comment by skullydazed** [comment]
> From the list of feedback you gave, how would you rate them

1. Speed- Not a must have, but important still. I saw that there was work in the main mkdocs repo around partital builds or on-demand builds which might help a lot with that. 
2. Navigation translation- Blocker. Defining a nav tree for each language would be ideal. Tying the translated title to the filename is workable. There may be other solutions to this we haven't identified yet.
3. Pages that don't exist in the primary language- Must have. As I think about this the standout use case is when reorganizing docs sometimes we need to rename or break-up pages, and it's not always possible to do that work in one PR across all languages. 
4. Everything in one directory- I don't have a good sense here. I think most of our translators are busy with back to school activity right now, I haven't gotten much feedback from them.

**Comment by ultrabug** [comment]
3. Pages that don't exist in the primary language- Must have. As I think about this the standout use case is when reorganizing docs sometimes we need to rename or break-up pages, and it's not always possible to do that work in one PR across all languages.

@skullydazed I believe that #59 fixes that blocker. would you give it a try please?

**Comment by AngryMane** [comment]
> Build Speed

As I mentioned at #74, I measured the time it takes to build with this plugin by cProfile and vmprof. 
- target project
    [mkdocs-test-sample.zip](https://github.com/ultrabug/mkdocs-static-i18n/files/7654351/mkdocs-test-sample.zip)
- log(cProfile)
    [cProfile_without_patch.LOG](https://github.com/ultrabug/mkdocs-static-i18n/files/7654345/cProfile_without_patch.LOG)
    You can refer by pstats command. e.g.) echo 'stats' | python3 -m pstats cProfile_without_patch.LOG
- log(vmprof)
    [vmprof_without_patch.LOG](https://github.com/ultrabug/mkdocs-static-i18n/files/7654347/vmprof_without_patch.LOG)
    You can refer by vmprofshow command. e.g.) vmprofshow --prune_level 15 --prune_percent 5 vmprof_without_patch.LOG
 
With the exception of _fix_search_duplicates, which is suggested for improvement in #74, the rest looks like it needs to support parallel builds on the mkdocs ...

**Comment by ultrabug** [comment]
Hi

I believe quite a lot of those features have been done

Now that #69 has also been merged, I find it fair to close this issue

If you feel otherwise, feel free to reopen thanks!
