### ISSUE TITLE
[Enhancement request] Listing of missing translated resources (page/images)

### ISSUE THREAD

**Issue by lasat** [ultrabug/mkdocs-static-i18n#58]
It would be helpfully if a log (INFO) could be written for each time a link/image reference fallback to the default language version of the image/page.

Example:
* default language: en
* current language: fr
* page contain link to: page1.md
* page1.fr.md doesn't exists -> INFO log is written
* same for images which not exists in the current language

Why would this be helpfully? See the progress of translation and the next steps to do.

**Comment by ultrabug** [comment]
Hi @lasat ; thanks for your feedback!

I'm unsure all users would be happy to see their logs spammed at the INFO level for missing translation pages so I'm pondering between a config option to enable this kind of tracing or to simply output this on the DEBUG level.

Would you have an opinion?

Also, friendly ping to @Stanzilla and @skullydazed if you may share your opinion here too (tell me to stop pinging you if that's painful)

**Comment by Stanzilla** [comment]
Hrm yeah, I think I would want that to be opt-in.

**Comment by skullydazed** [comment]
I can see the value in it, but definitely want to suppress those for production builds.

**Comment by lasat** [comment]
I'm happy with DEBUG if the log is prefixed by a filterable value -> for reporting and counting.

**Comment by ultrabug** [comment]
Ok, I have #59 to be merged first

**Comment by ultrabug** [comment]
@lasat I've added a log for when a **documentation page** is missing a translation 

> DEBUG     -  file topic2/README.en.md is missing translation in 'fr'

Inspecting the markdown source is not good since we allow for links to not be localized, so instead I'm looking for the documentation pages.

I hope that's enough and helpful mate
