### ISSUE TITLE
Second language structure different than default one

### ISSUE THREAD

**Issue by sirchampsblanc** [ultrabug/mkdocs-static-i18n#63]
Spanish version has index.html inside README/ but english version doesn't (english version works and spanish version doesn't). Rendered doc shows a 404 error when changing to spanish.

```
nav:
  - Home: README.md
```

This is the docs folder, README.md and README.es.md at the same level.

![Screenshot from 2021-10-20 14-38-00](https://user-images.githubusercontent.com/61840925/138094174-b59b65c7-8b3d-4c53-8a8e-91f9c135dc0f.png)

And this is the built docs, with differences between english and spanish versions. (spanish index.html is inside README/ when it shouldn't be).

![Screenshot from 2021-10-20 14-36-28](https://user-images.githubusercontent.com/61840925/138093829-61adb79e-799d-463f-81e0-56632335a9fa.png)

Any ideas why? Thanks!

EDIT: It's a 404 error when changing to spanish so obviously adding a /README makes it work but this is a workaround that i want to avoid (or changing spanish README.md references to include /README).

EDIT 2: If i rename README.md and README.es.md to index.md and index.es.md it works. I'd rather not do this but maybe makes the bug/problem more discoverable.

**Comment by ultrabug** [comment]
@sirchampsblanc do you have a public repository I can test this from maybe?

**Comment by ultrabug** [comment]
np mate, I found the problem, I'll be writing tests to demonstrate the error and validate the fix, then I'll put up a PR and tag you there!

Fix incoming! happy vacation mate ;)

**Comment by ultrabug** [comment]
Please check #68 and test it if you can? this should fix this issue

**Comment by sirchampsblanc** [comment]
> Please check #68 and test it if you can? this should fix this issue

It did fix the issue. Thanks!

**Comment by ultrabug** [comment]
version 0.22 is out
