### ISSUE TITLE
test example doesn't work locally in Windows

### ISSUE THREAD

**Issue by cacrespo** [ultrabug/mkdocs-static-i18n#7]
Hi! I copied all of files and then executed mkdocs build && mkdocs serve... everything OK. (I did it on Windows)
Then when I go to some pages the browser can't find them. There are some screenshots.
![image](https://user-images.githubusercontent.com/10950697/109142883-29544b80-773e-11eb-842f-f39be71d2723.png)
![image](https://user-images.githubusercontent.com/10950697/109142970-425cfc80-773e-11eb-8ee4-0de84062e748.png)
![image](https://user-images.githubusercontent.com/10950697/109143162-79331280-773e-11eb-9a7c-a33eadcff36d.png)

How can I help to fix the issue?
Thanks!

**Comment by ultrabug** [comment]
hi @cacrespo 

I'm confused because I can't reproduce this locally:

```
INFO    -  Documentation built in 0.13 seconds 
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
INFO    -  Documentation built in 0.10 seconds 
[I 210225 12:02:09 server:335] Serving on http://127.0.0.1:8000
[I 210225 12:02:09 handlers:62] Start watching changes
[I 210225 12:02:09 handlers:64] Start detecting changes
[I 210225 12:02:11 handlers:135] Browser Connected: http://127.0.0.1:8000/
[I 210225 12:02:13 handlers:135] Browser Connected: http://127.0.0.1:8000/topic1/
[I 210225 12:02:35 handlers:135] Browser Connected: http://127.0.0.1:8000/fr/
[I 210225 12:02:38 handlers:135] Browser Connected: http://127.0.0.1:8000/fr/topic1/
[I 210225 12:02:40 handlers:135] Browser Connected: http://127.0.0.1:8000/fr/topic2/
[I 210225 12:03:05 handlers:135] Browser Connected: http://127.0.0.1:8000/fr/topic1/
[I 210225 12:03:06 handlers:135] Browser Connected: http://127.0.0.1:8000/fr/
[I 210225 12:03:44 handlers:135] Browser Connected: http://127.0.0.1:8000/topic2/
```

Can you run `mkdocs build` and paste the `tree` of the `site` folder generated?

Here is mine:

```
site
├── 404.html
├── css
│   ├── base.css
│   ├── bootstrap.min.css
│   └── font-awesome.min.css
├── en
│   ├── index.html
│   ├── topic1
│   │   └── index.html
│   └── topic2
│       └── index.html
├── fonts
│   ├── fontawesome-webfont.eot
│   ├── fontawesome-webfont.svg
│   ├── fontawesome-webfont.ttf
│   ├── fontawesome-webfont.woff
│   ├── fontawesome-webfont.woff2
│   ├── glyphicons-halflings-regular.eot
│   ├── glyphicons-halflings-regular.svg
│   ├── glyphicons-halflings-regular.ttf
│   ├── glyphicons-halflings-regular.woff
│   └── glyphicons-halflings-regular.woff2
├── fr
│   ├── index.html
│   ├── topic1
│   │   └── index.html
│   └── topic2
│       └── index.html
├── img
│   ├── favicon.ico
│   └── grid.png
├── index.html
├── js
│   ├── base.js
│   ├── bootstrap.min.js
│   └── jquery-1.10.2.min.js
├── sitemap.xml
├── sitemap.xml.gz
├── topic1
│   └── index.html
└── topic2
    └── index.html
```

**Comment by cacrespo** [comment]
Sure!

Site
│   404.html
│   index.html
│   sitemap.xml
│   sitemap.xml.gz
│
├───css
│       base.css
│       bootstrap.min.css
│       font-awesome.min.css
│
├───en
│   │   index.html
│   │
│   ├───topic1
│   │   └───index.en
│   │           index.html
│   │
│   └───topic2
│       └───index.en
│               index.html
│
├───fonts
│       fontawesome-webfont.eot
│       fontawesome-webfont.svg
│       fontawesome-webfont.ttf
│       fontawesome-webfont.woff
│       fontawesome-webfont.woff2
│       glyphicons-halflings-regular.eot
│       glyphicons-halflings-regular.svg
│       glyphicons-halflings-regular.ttf
│       glyphicons-halflings-regular.woff
│       glyphicons-halflings-regular.woff2
│
├───fr
│   ├───index.fr
│   │       index.html
│   │
│   ├───topic1
│   │   └───index.fr
│   │           index.html
│   │
│   └───topic2
│       └───index.en
│               index.html
│
├───img
│       favicon.ico
│       grid.png
│
├───js
│       base.js
│       bootstrap.min.js
│       jquery-1.10.2.min.js
│
├───topic1
│   └───index.en
│           index.html
│
└───topic2
        index.html

**Comment by ultrabug** [comment]
We can see that we do not generate the same site you and I so I guess you changed something on the `mkdocs.yml` ? care to share it?

**Comment by cacrespo** [comment]
I didn't change anything, look:
```
site_name: MkDocs static i18n plugin demo
site_url: https://ultrabug.github.io/mkdocs-static-i18n
repo_url: https://github.com/ultrabug/mkdocs-static-i18n

plugins:
  - i18n:
      default_language: en
      languages:
        en: english
        fr: français
```
At night I will test on another PC with Ubuntu...

**Comment by ultrabug** [comment]
That's weird indeed... at you tried using the latest git version 0.5 I guess... keep me posted on your Ubuntu findings please

**Comment by cacrespo** [comment]
Hi @ultrabug!
I just tested it on Ubuntu and the site is rendered perfectly. Perhaps it is some incompatibility on Windows at the time of generating the strings of paths with the characters "\" ¿?

If you teach me how to test the plugin, I have no problem reviewing it thoroughly or doing the tests you consider necessary.

Thanks in advance!

**Comment by ultrabug** [comment]
> If you teach me how to test the plugin, I have no problem reviewing it thoroughly or doing the tests you consider necessary.

Well the generated file structure is actually tested on the project so you need to:
- clone this repo
- setup a virtual environment with python3.6+
- pip install -e .
- pip install -r requirements-qa.txt
- pytest -xs

And you should (when it works) see something like:

```
pytest -xs
============================================================== test session starts ===============================================================
platform linux -- Python 3.8.7, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/alexys/github/mkdocs-static-i18n
collected 6 items                                                                                                                                

tests/test_structure.py ......
========================================================= 6 passed, 2 warnings in 0.96s ==========================================================

```

**Comment by cacrespo** [comment]
Hello! I changed `plugin.py` and the test works fine :) Basically I changed` / `to` \\ `. I can't see how to fix this to run fine on both OS.
This is my code:
```
   def _get_translated_page(self, page, language, config):
        i18n_page = deepcopy(page)

        # there is a specific translation file for this lang
        for lang in self.all_languages:
            if self._is_translation_for(i18n_page.src_path, lang):
                i18n_page.name = page.name.replace(f".{lang}", "")
                if config.get("use_directory_urls") is False:
                    i18n_page.dest_path = i18n_page.dest_path.replace(
                        page.name, i18n_page.name
                    )
                    i18n_page.abs_dest_path = i18n_page.abs_dest_path.replace(
                        page.name, i18n_page.name
                    )
                    i18n_page.url = (
                        i18n_page.url.replace(page.name, i18n_page.name) or "."
                    )
                else:
                    i18n_page.dest_path = i18n_page.dest_path.replace(
                        f"{page.name}\\", ""
                    )
                    i18n_page.abs_dest_path = i18n_page.abs_dest_path.replace(
                        f"{page.name}\\", ""
                    )
                    i18n_page.url = i18n_page.url.replace(f"{page.name}/", "") or "."
                break

        # setup and copy the file to the current language path
        i18n_page.dest_path = f"/{language}/{i18n_page.dest_path}"
        i18n_page.abs_dest_path = i18n_page.abs_dest_path.replace(
            config["site_dir"], f"{config['site_dir']}/{language}"
        )
        i18n_page.url = (
            f"{language}/" if i18n_page.url == "." else f"{language}/{i18n_page.url}"
        )

        return i18n_page

    def _get_non_translated_page(self, page, page_lang, config):
        i18n_page = deepcopy(page)
        i18n_page.name = page.name.replace(f".{page_lang}", "")
        if config.get("use_directory_urls") is False:
            i18n_page.dest_path = page.dest_path.replace(f"{page.name}", i18n_page.name)
            i18n_page.abs_dest_path = page.abs_dest_path.replace(
                f"{page.name}", i18n_page.name
            )
            i18n_page.url = page.url.replace(page.name, i18n_page.name) or "."
        else:
            i18n_page.dest_path = page.dest_path.replace(f"{page.name}\\", "")
            i18n_page.abs_dest_path = page.abs_dest_path.replace(f"{page.name}\\", "")
            i18n_page.url = page.url.replace(f"{page.name}\\", "") or "."
```
