### ISSUE TITLE
Languages are unordered on drop-down

### ISSUE THREAD

**Issue by scmcca** [ultrabug/mkdocs-static-i18n#77]
Language options do not render in the same order defined in configuration. The default language always appears first, followed by the rest of my languages unordered. For example, my configuration looks like this:
```yml
languages:
  en: ... 
  fr: ...
  da: ...
  es: ...
  pt: ...
  ja: ...
```

And the render is unordered on every serve (results of 2 different serves below):
<img width="132" alt="Screen Shot 2021-12-01 at 9 42 20 AM" src="https://user-images.githubusercontent.com/62957380/147278534-0d6c5417-c945-4bcf-a793-90efa56d2d23.png">
<img width="139" alt="Screen Shot 2021-12-01 at 9 44 34 AM" src="https://user-images.githubusercontent.com/62957380/147278547-74a209db-e3e1-40b7-9ed6-1d508ae9d1d3.png">

I suspect this is because yaml does not consider order. Is there a fix that exists so that my languages appear in the same order I configure them? Thanks!

**Comment by ultrabug** [comment]
hello @scmcca ; you're right this is a good catch!

it's my fault because I use a set() to store the available languages, it's not yaml's fault :)

I'm fixing it
