### ISSUE TITLE
How to style/ relocate

### ISSUE THREAD

**Issue by negice** [ultrabug/mkdocs-static-i18n#8]
How would I style or relocate where the translation link is rendered?

**Comment by ultrabug** [comment]
Hi @negice 

Could you expand a bit on what you have in mind please?

You mean like instead of having `en/` for `en` in languages you'd like to have something else?

**Comment by negice** [comment]
By default when I use the plugin. It creates a <li>Fr</li> for [example](https://mkdocs-i18n.gitlab.io/mkdocs-i18n/) . I want to be able to style/relocate this link to somewhere else on the page. I am having some difficulty doing that

**Comment by ultrabug** [comment]
Sorry @negice I think you mistake the `mkdocs-static-i18n` with the `mkdocs-i18n` one.

This is the `mkdocs-static-i18n` github, the one you're talking about is hosted on Gitlab.com so I guess you'd like to head there for your question mate.

Hope this helps.

**Comment by negice** [comment]
Thanks @ultrabug I did not even realize that I was confusing the two plugins, It was my mistake. Thanks for taking the time to point this out to me and continue the great work.
