### ISSUE TITLE
Relative path warnings

### ISSUE THREAD

**Issue by Stanzilla** [ultrabug/mkdocs-static-i18n#83]
Hey there! Ever since I updated to the latest version (I might have skipped one), I've been getting a lot of relative path warnings again for a lot of files that are actually there. 

I can repro this on two systems, mac and Linux, with this repo https://github.com/ManticoreGamesInc/platform-documentation

**Comment by ultrabug** [comment]
Is that still on the development branch that it should be tested?

**Comment by Stanzilla** [comment]
> Is that still on the development branch that it should be tested?

Yep!

**Comment by ultrabug** [comment]
> Yep!

Darn, you've been busy guys, it's a hell to pull :)

**Comment by ultrabug** [comment]
please review & test https://github.com/ultrabug/mkdocs-static-i18n/pull/85

thanks!

**Comment by Stanzilla** [comment]
> please review & test #85
> 
> thanks!

That looks good! Only thing I'm not too sure about (which is not new though) is that it displays the missing pages warning twice, even with default_language_only enabled:

```
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - icons.md
              - generated/tags.md
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - icons.md
              - generated/tags.md
```

**Comment by ultrabug** [comment]
Those missing pages info are because we generate a nav for every language, can't do any other way sorry

**Comment by Stanzilla** [comment]
Alright, thank you!

**Comment by Stanzilla** [comment]
> Those missing pages info are because we generate a nav for every language, can't do any other way sorry

After updating to 0.41, I now get the info print 3 times, is that related to language options changes?

**Comment by ultrabug** [comment]
> After updating to 0.41, I now get the info print 3 times, is that related to language options changes?

Yes, and I see that I missed skipping the `on_nav` for languages with `build: False` so that's my bad, thanks for the hint.

**Comment by ultrabug** [comment]
https://github.com/ultrabug/mkdocs-static-i18n/commit/b1523f554cfe9adbc5623786a3e4acbb01c9cac8

**Comment by Stanzilla** [comment]
hah, glad I could help!
