### ISSUE TITLE
[Bug] Plugin breaks mkdocs-material tag index generation

### ISSUE THREAD

**Issue by Stanzilla** [ultrabug/mkdocs-static-i18n#92]
When using mkdocs-material's tags index generation, the `[TAGS]` section is not populated, this is a regression and used to work before.

See https://docs.coregames.com/generated/tags/

mkdocs-material docs: https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#adding-a-tags-index

**Comment by ultrabug** [comment]
@Stanzilla if I switch to your development branch, install the requirements, build... I get a tags page populated

What should I do to reproduce?

**Comment by Stanzilla** [comment]
Well that is odd, I can see it working on a deployed production branch, broken on the deployed development branch and broken locally. So the difference has to be some config.

**Comment by ultrabug** [comment]
Closing, if you find out please reopen

**Comment by Stanzilla** [comment]
Looks like it works now anyway, will do so when it breaks again but sounds like it is/was something mit material anyway.
