### ISSUE TITLE
[BUG] mkdocs minify plugin is broken after upgrade to mkdocs-static-i18n=="0.30"

### ISSUE THREAD

**Issue by lasat** [ultrabug/mkdocs-static-i18n#94]
Today I've tried to upgrade this plugin from "0.20" to the latest version "0.41" but recognize that afterwards the out styling is back to materials standard settings. 

I've found that this behavior started with "0.30" and only if we have the minify-plugin=="0.5.0" enabled (page contain links to the not minified version of css/js files).
I've quickly checked the [code changes](https://github.com/ultrabug/mkdocs-static-i18n/compare/0.22...0.30), but my knowledge ends here.

I've only changed this plugin so I would like to ask here: Did I miss something or is this a bug?

**Comment by ultrabug** [comment]
@lasat hi, thanks for reporting this.

It's impossible for me to understand exactly your problem without a way to reproduce it. Is there a public repo I could clone? Could you do before/after screenshots or page code differences maybe?

I'll try to spend 15min on it by myself but I'm not sure to know what I'm looking for exactly sorry.

**Comment by lasat** [comment]
Hi @ultrabug, sorry for not  being clear enough and waste your time.

Please see https://github.com/lasat/mkdocs-static-i18n_minify where I demonstrate the problem

**Comment by ultrabug** [comment]
version 0.44 is out mate, enjoy
