### ISSUE TITLE
Support for multi-level nav

### ISSUE THREAD

**Issue by sukki37** [ultrabug/mkdocs-static-i18n#96]
I found that `nav_translations` can only support configuring the top-level nav. I wanna know whether [mkdocs-static-i18n](https://github.com/ultrabug/mkdocs-static-i18n) support to specify multi-language nav in `mkdoc.yml`  like follows:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/77312370/156374567-e58aa312-d8e0-4473-adbe-e8648d27cf62.png">

Thanks.

**Comment by ultrabug** [comment]
Hello @sukki37 

The translations apply to **ALL** levels because they apply on titles, not on the navigation tree structure.

Easy :)

**Comment by sukki37** [comment]
> Hello @sukki37
> 
> The translations apply to **ALL** levels because they apply on titles, not on the navigation tree structure.
> 
> Easy :)

Thank you for the reply. So can I say that only the top folder name can be translated?  How about there are multi-level directories in the `docs` folder, the subdirectory name can be translated as well or not?

**Comment by ultrabug** [comment]
@sukki37 yes, just add the translations, ignore the "sub"directory structure
